x-postgres-variables: &postgres-variables
  POSTGRES_DB: "${DB__DB_NAME}"
  POSTGRES_USER: "${DB__USERNAME}"
  POSTGRES_PASSWORD: "${DB__PASSWORD}"
  POSTGRES_PORT: "${DB__PORT}"

x-rmq-variables: &rmq-variables
  RABBITMQ_DEFAULT_USER: "${RABBIT__USERNAME}"
  RABBITMQ_DEFAULT_PASS: "${RABBIT__PASSWORD}"
  RABBITMQ_DEFAULT_VHOST: "${RABBIT__VHOST}"

services:
  backend:
    container_name: backend-${COMPOSE_PROJECT_NAME}
    ports:
      - "127.0.0.1:8080:8000"
    volumes:
      - ./src:/code/src
      - ./migrations:/code/migrations
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: >
      sh -c " alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app_network

  postgres:
    container_name: postgres-${COMPOSE_PROJECT_NAME}
    image: postgres:17.6
    environment:
      <<: *postgres-variables
    ports:
      - "5432"
    healthcheck:
      interval: 3s
      retries: 2
      test: "pg_isready -U ${DB__USERNAME} -d ${DB__DB_NAME}"
      timeout: 2s
    #volumes:
    #  - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

  scheduler:
    container_name: scheduler-${COMPOSE_PROJECT_NAME}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/code/src
    networks:
      - app_network
    command: [ "sh", "-c", "python3 -m src.scheduler" ]

  payment-consumer:
    container_name: payment-consumer-${COMPOSE_PROJECT_NAME}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/code/src
    networks:
      - app_network
    command: [ "sh", "-c", "python3 -m src.consumer" ]

  rabbitmq:
    container_name: rabbitmq-${COMPOSE_PROJECT_NAME}
    image: rabbitmq:3.13-management
    environment:
      <<: *rmq-variables
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    #volumes:
    #  - ./rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres:

networks:
  app_network:
    driver: bridge
    name: app_network
