"""init outbox table

Revision ID: 9663281bf3af
Revises: db44e5f72676
Create Date: 2026-04-20 18:36:39.006766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9663281bf3af'
down_revision: Union[str, Sequence[str], None] = 'db44e5f72676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_table',
    sa.Column('event_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('routing_key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_table')
    # ### end Alembic commands ###
