"""fix payment model

Revision ID: 13eb3936a514
Revises: 9663281bf3af
Create Date: 2026-04-20 22:43:55.556405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13eb3936a514'
down_revision: Union[str, Sequence[str], None] = '9663281bf3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('idempotency_key', sa.UUID(), nullable=False))
    op.drop_column('payment', 'Idempotency_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('Idempotency_key', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('payment', 'idempotency_key')
    # ### end Alembic commands ###
